/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repaso;

import javax.swing.JOptionPane;

/**
 *
 * @author low
 */
public class nuevoProyecto extends javax.swing.JFrame {

    /**
     * Creates new form nuevoProyecto
     */
    
    private String NombreP;
    private int NumDelP;
    private String NombreD;
    private boolean listo = false;
    
    public String getNombreP (){
        return NombreP;
    }
    
    public void setListo(boolean unListo){
        listo = unListo;
    }
    
    public boolean getListo(){
        return listo;
    }
    
    public int getNumDelP (){
        return NumDelP;
    }
    
    public String getNombreD (){
        return NombreD;
    }
    
    public void cargarProyecto (){
        if (!txtNombreDelProyecto.getText().equals("ingrese el nombre del proyecto"))
            NombreP = (txtNombreDelProyecto.getText());
        else
            NombreP = "";
        if (!spnNumeroDelProyecto.getValue().equals(0))
            NumDelP = (int) spnNumeroDelProyecto.getValue();
        else
            NumDelP = 0;
        if (!txtNombreDelDirector.getText().equals("ingrese el nombre del director"))
            NombreD = (txtNombreDelDirector.getText());
        else
            NombreD = "";
    }
    
    public void reiniciarProyecto (){
        txtNombreDelProyecto.setText("ingrese el nombre del proyecto");
        NombreP = "";
        spnNumeroDelProyecto.setValue(0);
        NumDelP = 0;
        txtNombreDelDirector.setText("ingrese el nombre del director");
        NombreD = "";
    }
            
    public nuevoProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        lblNombreDelProyecto = new javax.swing.JLabel();
        txtNombreDelProyecto = new javax.swing.JTextField();
        lblNumeroDelProyecto = new javax.swing.JLabel();
        lblNombreDelDirector = new javax.swing.JLabel();
        txtNombreDelDirector = new javax.swing.JTextField();
        spnNumeroDelProyecto = new javax.swing.JSpinner();
        lblNuevoProyecto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblNombreDelProyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreDelProyecto.setText("Nombre del proyecto:");

        txtNombreDelProyecto.setText("ingrese el nombre del proyecto");
        txtNombreDelProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblNumeroDelProyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumeroDelProyecto.setText("Numero del proyecto:");

        lblNombreDelDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreDelDirector.setText("Nombre del director:");

        txtNombreDelDirector.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreDelDirector.setText("ingrese el nombre del director");
        txtNombreDelDirector.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreDelDirector.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        spnNumeroDelProyecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblNuevoProyecto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNuevoProyecto.setText("Nuevo Proyecto");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNuevoProyecto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreDelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreDelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNumeroDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(spnNumeroDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNombreDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDelProyecto)
                    .addComponent(txtNombreDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroDelProyecto)
                    .addComponent(spnNumeroDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreDelDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.cargarProyecto();
        JOptionPane.showMessageDialog(this,"nombre del Proyecto: "+ NombreP+
                                           " codigo del proyecto: "+ NumDelP+ 
                                           " nombre del director: "+ NombreD);
        if ( getNombreP().equals("") || getNumDelP() == 0 || getNombreD().equals(""))
            this.setVisible(true);
        else{
            this.setVisible(false);
            setListo(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.reiniciarProyecto();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNombreDelDirector;
    private javax.swing.JLabel lblNombreDelProyecto;
    private javax.swing.JLabel lblNuevoProyecto;
    private javax.swing.JLabel lblNumeroDelProyecto;
    private javax.swing.JSpinner spnNumeroDelProyecto;
    private javax.swing.JTextField txtNombreDelDirector;
    private javax.swing.JTextField txtNombreDelProyecto;
    // End of variables declaration//GEN-END:variables
}
